### ISSUE TITLE
Disable/Turn Off Wifi LED

### ISSUE THREAD

**Issue by benmprojects** [arendst/Sonoff-Tasmota#3679]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
No, The flashing LED is rather annoying
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
An option to disable the Wifi LED from the web dashboard
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
Tape over the LED :)
**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by wasi54** [comment]
See https://github.com/arendst/Sonoff-Tasmota/wiki/Commands
LedPower | 0 / off | Turn led AND LedState Off
Please close the Issue if your Problem ist solved

**Comment by Frogmore42** [comment]
You can send that command from the web UI.

**Comment by ascillato2** [comment]
Closing as your question has been addressed. Please, ask to reopen if needed.

**Comment by vel2000** [comment]
>  LedPower | 0 / off | Turn led AND LedState Off

does NOT solve the problem!
The wifi LED is still flashing, if there is no Wifi-connection.
"LedState 0" does not help either...

**Comment by andreas-bulling** [comment]
Same here. Also `LEDPower 0; SetOption31 1` doesn't help.

Maybe https://github.com/arendst/Sonoff-Tasmota/issues/488 explains why?

**Comment by andreas-bulling** [comment]
Didn't help in my case unfortunately :(

**Comment by john-arvid** [comment]
Same problem here.
@ascillato2 Could you open this again or should it be created a new issue?

**Comment by ascillato** [comment]
Hi, please address your issue in the Tasmota Support Chat

**Comment by topperwh** [comment]
1) go to your Sonoff IP Address
2) click "console"
3) LedPower 0  (Copy, paste & no semicolon) 

--- That MQTT protocol will stop the LED blink light.

**Comment by john-arvid** [comment]
> 1. go to your Sonoff IP Address
> 2. click "console"
> 3. LedPower 0     (Copy, paste & no semicolon) press enter
> 4. LedState 0      press enter
> 
> --- That MQTT protocol will stop the LED blink light.

Does not work on the board I am using. D1 Mini

I asked on Tasmota Support Chat and the only suggestion was to remove the led. (Or cut the trace)

**Comment by 8osman** [comment]
Led Power 0

Then

SetOption31 1

From firmware 6.2.0

Worked on mine.

**Comment by 8osman** [comment]
This was from the wiki commands

**Comment by john-arvid** [comment]
Not working for me, using firmware 6.4.1(sensors)

**Comment by john-arvid** [comment]
I have tested a bit more and found that when I was using GPIO2 with my AM2301 sensor the led blinked no matter what commands I used.
But when I set the configuration on GPIO2 to none, the led stopped blinking.
Also when I use GPIO4 with the AM2301 sensor, the led is not blinking.
Even if I am sending MQTT messages every 10 seconds there is no blinking from the led.

Is this a hardware or software problem?

**Comment by arendst** [comment]
Your D1 mini led is hardwired to GPIO02. So anything you connect to GPIO02 will also blink the Led. The chat also told you that the led is hardwired. So...

**Comment by john-arvid** [comment]
Ok, I understand.
Hope this can be of help to others also. Try the commands or another gpio.

**Comment by 84wb** [comment]
> Hope this can be of help to others also.
It was. Thanks!

**Comment by HenniC4** [comment]
That blinking seems to be Tasmota desperately crying for its MQTT Server. Setoption3 0 did the trick for me.

**Comment by JamFfm** [comment]
MQTT seems to have impact on the green LED. Turning MQTT off results in LED on all the time.

LedPower 0
AND
Setoption3 0
in the console did the trick for me. 

Thanks all for your help.

**Comment by dachshund-digital** [comment]
LedPower 0 and Setoption3 0 did not work for me on firmware 9.4.  Any suggestions?  Trying to explicitly control the onboard led.

**Comment by MikeTraceur** [comment]
I could help myself going into the template and set the pin containing Led* to None. I know it is quick and dirty
